### ISSUE TITLE
"sidzIgnoreMagicNumbers" is not working for numeric-strings

### ISSUE THREAD

**Issue by voku** [sidz/phpstan-rules#23]
Hi, and thanks for this phpstan addon. I use it in a legay php project and step-by-step the magic numbers will be replaced with constants that I can understand. 👍 

---

The situation: I updated the php application from 7.4 to 8.3 and now I use vesion `0.4.3` but I see many new errors from numerc-strings. For now I will use `sidzIgnoreNumericStrings: true` but I think ignoring should be work also for numeric-strings.

The problem: `ignoreNumber()` will check the type of the config value but numeric-strings are not allowed here, I see messages like this: `The item 'parameters › sidzIgnoreMagicNumbers › 2' expects to be number, '0' given.` if I try to add `'2'` or `"2"` in for `sidzIgnoreMagicNumbers`.

Code:
```php
    /**
     * @param LNumber|DNumber $scalar
     */
    private function ignoreNumber(Expr $scalar): bool
    {
        return in_array($scalar->value, $this->ignoreMagicNumbers, true);
    }
```

Possible fix: ?
```php
    /**
     * @param LNumber|DNumber $scalar
     */
    private function ignoreNumber(Expr $scalar): bool
    {
        $ignoreMagicNumbersStrings = array_map(function($obj) {
            return (string) $obj;
        }, $this->ignoreMagicNumbers);

        return in_array($scalar->value, $this->ignoreMagicNumbers, true) || in_array($scalar->value, $ignoreMagicNumbersStrings, true);
    }
```

**Comment by sidz** [comment]
Thanks @voku for highlighting this issue.

We have 2 options here:
- Modify schema and allow numeric values as part of config
- Convert all values to strings and compare strings

I decided that allowing numbers and numeric strings as a config option leads to duplication like: `sidzIgnoreMagicNumbers: [0, 1, "0", "1"]` and choose the second option


So I slightly modified the code proposed by you and raised a pull request https://github.com/sidz/phpstan-rules/pull/24

**Comment by sidz** [comment]
Fixed and released in https://github.com/sidz/phpstan-rules/releases/tag/0.4.4 @voku
