### ISSUE TITLE
dependency "nikic/php-parser" can be a dev-dependency, or? 

### ISSUE THREAD

**Issue by voku** [sidz/phpstan-rules#25]
I skiped the installation of "nikic/php-parser" and it's still working because phpstan/phpstan (the phar file) has his dependency already included, or?

**Comment by sidz** [comment]
Good catch @voku.

PR: https://github.com/sidz/phpstan-rules/pull/26

**Comment by sidz** [comment]
https://github.com/sidz/phpstan-rules/releases/tag/0.4.5 released
